#!/usr/bin/env python
#
# Copyright (C) STMicroelectronics Ltd. 2012
#
# This file is part of ATOS.
#
# ATOS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License v2.0
# as published by the Free Software Foundation
#
# ATOS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# v2.0 along with ATOS. If not, see <http://www.gnu.org/licenses/>.
#
#
# Checks python dependencies for ATOS
#
# Usage: python_checks
#
# Returns exit status 0 iif all dependencies are available.
# Returns exit status 1 otherwise.
#

errors=0
try:
    print "Check python pygraph...",
    import pygraph
    print "ok"
except:
    print "not installed: please install from: http://code.google.com/p/python-graph"
    errors += 1
try:
    print "Check python pygraph-dot...",
    import pygraph.readwrite.dot
    print "ok"
except:
    print "not installed: please install from: http://code.google.com/p/python-graph"
    errors += 1

if errors:
    exit(1)

