#!/usr/bin/env python
#
# Copyright (C) STMicroelectronics Ltd. 2012
#
# This file is part of ATOS.
#
# ATOS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License v2.0
# as published by the Free Software Foundation
#
# ATOS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# v2.0 along with ATOS. If not, see <http://www.gnu.org/licenses/>.
#
#
# Checks python dependencies for ATOS
#
# Usage: python_checks
#
# Returns exit status 0 iif all dependencies are available.
# Returns exit status 1 otherwise.
#

errors=0
try:
    print "Check python jsonlib...",
    import jsonlib
    print "ok"
except:
    print "not installed: please install from: https://github.com/guillon/python-jsonlib"
    errors += 1
try:
    print "Check python jsonpath...",
    import jsonpath
    print "ok"
except:
    print "not installed: please install from: http://pypi.python.org/pypi/jsonpath"
    errors += 1
try:
    print "Check python pylab matplotlib...",
    import pylab
    print "ok"
except:
    print "not installed: please install from: http://www.scipy.org/PyLab or from your package manager python-matplotlib"
    print "warning: atos-graph will not be available"
try:
    print "Check python pylab matplotlib tk backend...",
    import matplotlib.backends.backend_tkagg
    print "ok"
except:
    print "not installed: please install from: http://www.scipy.org/PyLab or from your package manager python-matplotlib-tk"
    print "warning: atos-graph will not be available"

if errors:
    exit(1)

